import Head from 'next/head';
// import Image from 'next/image';
import { Inter } from '@next/font/google';
import { ActionButton, Sidebar } from '../common';
import AddCircleIcon from '@mui/icons-material/AddCircle';

// import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <main>
        <h1>Invoice App</h1>
        <ActionButton
          bgcolor="#7C5DFA"
          startIcon={
            <AddCircleIcon sx={{ color: '#fff', width: 50, height: 50 }} />
          }
        >
          New Invoice
        </ActionButton>
      </main>
    </>
  );
}
